dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion"
    implementation "org.koin:koin-androidx-viewmodel:$koinVersion"

    implementation enforcedPlatform("androidx.compose:compose-bom:$composeBomVersion")
    implementation "androidx.activity:activity-compose:$activityComposeVersion"
    implementation "androidx.compose.foundation:foundation"
    implementation "androidx.compose.material3:material3"
    implementation "androidx.compose.material:material-icons-extended"
    implementation "androidx.compose.ui:ui"
    implementation "androidx.compose.ui:ui-tooling-preview"
    debugImplementation "androidx.compose.ui:ui-tooling"
    implementation "androidx.navigation:navigation-compose:$navigationComposeVersion"
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:$lifecycleComposeVersion") {
        version { strictly lifecycleComposeVersion }
    }
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutinesVersion") {
        version { strictly coroutinesVersion }
    }
    implementation "io.coil-kt:coil-compose:$coilVersion"
    implementation "androidx.media3:media3-exoplayer:$media3Version"
    implementation "androidx.media3:media3-datasource-okhttp:$media3Version"

    implementation "androidx.appcompat:appcompat:$appcompatVersion"
    implementation "androidx.browser:browser:$browserVersion"
    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycleVersion"
    implementation "androidx.work:work-runtime-ktx:$workVersion"
    implementation "androidx.core:core-ktx:$coreKtxVersion"
    implementation "androidx.fragment:fragment-ktx:$fragmentKtxVersion"
    implementation "androidx.security:security-crypto:$securityCryptoVersion"

    implementation "io.reactivex.rxjava2:rxjava:$rxJavaVersion"
    implementation "io.reactivex.rxjava2:rxkotlin:$rxKotlinVersion"
    implementation "io.reactivex.rxjava2:rxandroid:$rxAndroidVersion"
    implementation "com.jakewharton.rxbinding3:rxbinding-core:$rxBindingVersion"
    implementation "com.jakewharton.rxbinding3:rxbinding-appcompat:$rxBindingVersion"
    implementation "com.f2prateek.rx.preferences2:rx-preferences:$rxPreferencesVersion"
    implementation "com.github.rubengees:rxbus:$rxBusVersion"
    implementation "com.uber.autodispose:autodispose-ktx:$autoDisposeVersion"
    implementation "com.uber.autodispose:autodispose-android-archcomponents-ktx:$autoDisposeVersion"

    implementation "com.google.android.material:material:$materialComponentsVersion"
    implementation "androidx.preference:preference:$preferenceVersion"
    implementation "com.mikepenz:iconics-core:$iconicsVersion"
    implementation "com.mikepenz:iconics-views:$iconicsVersion"
    implementation "com.mikepenz:community-material-typeface:$communityMaterialTypefaceVersion"
    implementation "com.afollestad.material-dialogs:core:$materialDialogsVersion"
    implementation "me.zhanghai.android.materialprogressbar:library:$materialProgressBarVersion"
    implementation "me.zhanghai.android.customtabshelper:library:$customtabsHelperVersion"

    implementation "com.github.proxer:ProxerLibJava:$proxerLibVersion"
    implementation "com.jakewharton.threetenabp:threetenabp:$threetenVersion"
    implementation "com.squareup.okhttp3:okhttp:$okHttpVersion"
    implementation "com.squareup.okhttp3:okhttp-brotli:$okHttpVersion"
    implementation "com.squareup.okhttp3:logging-interceptor:$okHttpVersion"
    implementation "com.squareup.okio:okio:$okioVersion"
    implementation "com.squareup.moshi:moshi:$moshiVersion"
    implementation "com.squareup.moshi:moshi-adapters:$moshiVersion"
    implementation "com.github.rubengees:kotterknife:$kotterknifeVersion"
    implementation "com.gojuno.koptional:koptional-rxjava2-extensions:$kOptionalVersion"
    implementation "me.saket:better-link-movement-method:$betterLinkMovementMethodVersion"

    implementation("com.github.rubengees:hawk:$hawkVersion") {
        exclude module: "gson"
    }

    implementation "com.jakewharton.timber:timber:$timberVersion"

    releaseImplementation "cat.ereza:customactivityoncrash:$customActivityOnCrashVersion"
    logReleaseImplementation "cat.ereza:customactivityoncrash:$customActivityOnCrashVersion"

    kapt "com.squareup.moshi:moshi-kotlin-codegen:$moshiVersion"

    compileOnly "com.github.pengrad:jdk9-deps:$jdkDeps9Version"
}